name: blue_bird_cli
description: Blue Bird CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ^0.1.0
  glob: ^2.0.2
  lcov_parser: ^0.1.2
  mason: ">=0.1.0-dev.39 <0.1.0-dev.40"
  mason_logger: ^0.2.2
  meta: ^1.3.0
  path: ^1.8.0
  pub_updater: ^0.2.1
  pubspec_parse: ^1.2.0
  stack_trace: ^1.10.0
  universal_io: ^2.0.4
  usage: ^4.0.2
  very_good_test_runner: ^0.1.2

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

executables:
  blue_bird:
