name: blue_bird_cli
description: A Command-Line Interface for generating complex large-scale Flutter project and package architectures.
version: 0.1.4
repository: https://github.com/Abel1027/blue_bird_cli

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ^0.2.0
  glob: ^2.1.1
  lcov_parser: ^0.1.2
  mason: ^0.1.0-dev.40
  mason_logger: ^0.2.3
  meta: ^1.8.0
  path: ^1.8.3
  pub_updater: ^0.2.3
  pubspec_parse: ^1.2.1
  stack_trace: ^1.11.0
  universal_io: ^2.0.4
  usage: ^4.1.0
  very_good_test_runner: ^0.1.2

dev_dependencies:
  build_runner: ^2.3.3
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.22.2
  very_good_analysis: ">=3.1.0 <5.0.0"

executables:
  blue_bird:
